name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8  # for lint step

      - name: Run CI tests
        run: |
          python tests/run_ci_tests.py

      - name: Run lint (continue on error)
        run: |
          make lint || echo "⚠️ Lint errors found - these are style issues that don't affect functionality"
        continue-on-error: true